[env]
TERM = "xterm-256color"

[window]
padding.x = 8 
padding.y = 8

decorations = "Buttonless"

# opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 18

[cursor]
style = "underline"

[general]
import = [
  "~/.config/alacritty/themes/themes/catppuccin.toml"
]

